### ISSUE TITLE
AttributeError: 'attrdict' object has no attribute 'unlabeled_category'

### ISSUE THREAD

**Issue by skr3178** [LungCellAtlas/mapping_data_to_the_HLCA#1]
How to resolve this issue:
Error is at line" freeze_dropout = True". 

```
for batch in query_batches: # this loop is only necessary if you have multiple batches, but will also work for a single batch.
    print("Batch:", batch)
    query_subadata = query_data[query_data.obs[batch_variable] == batch,:].copy()
    print("Shape:", query_subadata.shape)
    # load model and set relevant variables:
    model = sca.models.SCANVI.load_query_data(
        query_subadata,
        dir_ref_model,
        freeze_dropout = True
    )
    model._unlabeled_indices = np.arange(query_subadata.n_obs)
    model._labeled_indices = []
    # now train surgery model using reference model and target adata
    model.train(
        n_epochs_semisupervised=surgery_epochs,
        train_base_model=False,
        semisupervised_trainer_kwargs=dict(
            metrics_to_monitor=["accuracy", "elbo"], 
            weight_decay=0,
            early_stopping_kwargs=early_stopping_kwargs_surgery
        ),
        frequency=1
    )
    surgery_path = os.path.join(dir_out,batch)
    if not os.path.exists(surgery_path):
        os.makedirs(surgery_path)
    model.save(surgery_path, overwrite=True)
```

Thank you

**Comment by adamgayoso** [comment]
The issue is related to API changes in scvi-tools recently.  I will try to coordinate with the authors to update the code

**Comment by adamgayoso** [comment]
alas the issue is on our end, we are patching a release asap. that said, the notebook here should be updated with the latest code as this code won't work either way. We are building a notebook for our tutorials using this dataset!

**Comment by skr3178** [comment]
> 

Thank you so much!

**Comment by adamgayoso** [comment]
The draft tutorial can be found [here](https://colab.research.google.com/drive/1bikxrNT1fnp8giwg8aMIEiLT06tW9IRp?usp=sharing). We will include this in the next scvi-tools release.

We use pynndescent neighbors and minimum distortion embedding for viz and this makes it really fast to run!

**Comment by adamgayoso** [comment]
Tutorial now [here](https://docs.scvi-tools.org/en/stable/tutorials/notebooks/query_hlca_knn.html). @LisaSikkema you may consider updating your notebook to reflect the API changes we have here (which are stable for the future).

**Comment by skr3178** [comment]
Thank you so much!

**Comment by LisaSikkema** [comment]
Thanks @adamgayoso! We stuck to that older version as that is the version we used for the paper hence tested carefully.. are the differences between our version and the new version mostly streamlining of code or also changes in the algorithm etc.?
