### ISSUE TITLE
AttributeError: module 'scvi' has no attribute 'model'

### ISSUE THREAD

**Issue by bitcometz** [LungCellAtlas/mapping_data_to_the_HLCA#2]
hello，

Thanks for your great work ！
I am trying to map my data to HLCA. First, I learn from your toturials:

https://docs.scvi-tools.org/en/stable/tutorials/notebooks/query_hlca_knn.html

However, I met some errors after I run that code:
```python
ref_model_path = "HLCA_reference_model"
scvi.model.SCANVI.prepare_query_anndata(query_data, ref_model_path)
```

Errors:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_20928/291405550.py in <module>
      1 ref_model_path = "HLCA_reference_model"
----> 2 scvi.model.SCANVI.prepare_query_anndata(query_data, ref_model_path)

AttributeError: module 'scvi' has no attribute 'model'
```

software versions:
```
scanpy                    1.8.1                    pypi_0    pypi
scarches                  0.5.1                    pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scikit-misc               0.1.4                    pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
scvi                      0.6.8                    pypi_0    pypi
scvi-tools                0.13.0                   pypi_0    pypi
```

Best

**Comment by LisaSikkema** [comment]
Hi there! 
Looks like the notebook that you're working with is not the one from this GitHub repo, but the one that was released by scvi-tools. I'm not sure what their version requirements are.  @adamgayoso might be able to say more about this.
In the meantime, we're looking into adapting our notebook to update our code and versions to align with the latest scvi-tools! Updates should come soon!

**Comment by adamgayoso** [comment]
Hi @bitcometz -- the tutorial requires the latest release (0.15.2). That sort of error message leads me to think there has been some sort of installation issue.

**Comment by bitcometz** [comment]
Thanks ！！！

I update scvi and it seems work now ! however, when I run the following code, it takes for hours and it is still running,
I wonder if this is normal.

```python
X_train          = adata.X
ref_nn_index     = pynndescent.NNDescent(X_train)
ref_nn_index.prepare()
```

Best

**Comment by adamgayoso** [comment]
this is not normal, it takes not a lot of time on google colab which has like 2 cores. I would check to see that it's installed correctly.

**Comment by bitcometz** [comment]
Thanks ！
After about 4 hours，it finished the job and than I met another error:
https://github.com/LungCellAtlas/mapping_data_to_the_HLCA/issues/3

**Comment by LisaSikkema** [comment]
Are you using GPU? (Not sure if it can even run without, but it would def. be a lot slower)

**Comment by LisaSikkema** [comment]
Ah just saw your comment in another issue. Okay closing this issue now.

**Comment by clee700** [comment]
Hello, I am trying to follow this tutorial: 
https://docs.scvi-tools.org/en/stable/tutorials/notebooks/tabula_muris.html

And I run into the same issue where module 'scvi' has no attribute 'model' 

Thank you! 

<img width="242" alt="image" src="https://user-images.githubusercontent.com/112990107/192169879-c419c481-aac2-4947-b847-c4aeba7001eb.png">

**Comment by adamgayoso** [comment]
Do you have a folder or file named scvi? This would clash with the namespace

**Comment by clee700** [comment]
No, I don't have any folders/files called scvi. 
I tried to import scvi.model and got this error: 

import scvi.model.SCVI
ImportError: cannot import name 'settings' from 'scvi' (/home/christy/.local/lib/python3.8/site-packages/scvi/__init__.py)

**Comment by clee700** [comment]
Also I realize now that there is an scvi folder in the python3.8/site-packages folder, so I deleted it.. 
the error is now: 

ModuleNotFoundError: No module named 'scvi.model'

**Comment by 183136** [comment]
is this problem solved?

**Comment by stela2502** [comment]
pip3 install --upgrade scvi-tools 

Did install scvi-tool version 0.20.1 for me today (2023 08 18).
And the problem was gone.

**Comment by sondvo** [comment]
somehow the command 
`pip install --upgrade scvi-tools `
does not update scvi. My scvi was still in version 0.8.x, which causes the problem stated above

After uninstalling, and then installing, my scvi is updated to 1.1.2, which solved the problem!
```
pip uninstall scvi-tools
pip  install --upgrade scvi-tools
```

**Comment by LYT-academic** [comment]
> Do you have a folder or file named scvi? This would clash with the namespace

ohh, that's exactly what I did, I named my processing file as 'scvi.py'.... Thank you very much!
