### ISSUE TITLE
model.pt not available

### ISSUE THREAD

**Issue by dvdylus** [LungCellAtlas/mapping_data_to_the_HLCA#4]
Hi,

I am trying to use your notebook to map some of my data to HLCA but when I try to run the test dataset the following problem occurs:

`INFO     No backup URL provided for missing file ../data/HLCA_reference_model/model.pt      `
                      
This file does not exist in the automatically downloaded data directory. Any suggestions what to do?

Thank you.

Best,
David

**Comment by LuckyMD** [comment]
Hi @dvdylus,

You can download the model from https://zenodo.org/record/6337966#.ZA5y-LTMKeB
I guess this is only really mentioned in the paper, but not so well in the README here. It should be in the reference model zip file.

**Comment by LisaSikkema** [comment]
Latest model is now on Zenodo: https://zenodo.org/record/7599104#.ZGJBVS8Rpqs
Updated mapping notebook just submitted as a pull request to scArches, see PR [here](https://github.com/theislab/scarches/pull/191) and notebook [here](https://github.com/theislab/scarches/blob/hlca_tutorial_improvements/notebooks/hlca_map_classify.ipynb).
Will close this issue now!
